//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xin.Basic.NationalAQIPublishDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityAQIPublishLive", Namespace="http://schemas.datacontract.org/2004/07/Xin.AQS.ClassLibrary")]
    [System.SerializableAttribute()]
    public partial class CityAQIPublishLive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnheathfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((object.ReferenceEquals(this.AQIField, value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO {
            get {
                return this.COField;
            }
            set {
                if ((object.ReferenceEquals(this.COField, value) != true)) {
                    this.COField = value;
                    this.RaisePropertyChanged("CO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityCode {
            get {
                return this.CityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CityCodeField, value) != true)) {
                    this.CityCodeField = value;
                    this.RaisePropertyChanged("CityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Measure {
            get {
                return this.MeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasureField, value) != true)) {
                    this.MeasureField = value;
                    this.RaisePropertyChanged("Measure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2 {
            get {
                return this.NO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NO2Field, value) != true)) {
                    this.NO2Field = value;
                    this.RaisePropertyChanged("NO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3 {
            get {
                return this.O3Field;
            }
            set {
                if ((object.ReferenceEquals(this.O3Field, value) != true)) {
                    this.O3Field = value;
                    this.RaisePropertyChanged("O3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10 {
            get {
                return this.PM10Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM10Field, value) != true)) {
                    this.PM10Field = value;
                    this.RaisePropertyChanged("PM10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5 {
            get {
                return this.PM2_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5Field, value) != true)) {
                    this.PM2_5Field = value;
                    this.RaisePropertyChanged("PM2_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryPollutant {
            get {
                return this.PrimaryPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPollutantField, value) != true)) {
                    this.PrimaryPollutantField = value;
                    this.RaisePropertyChanged("PrimaryPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityField, value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2 {
            get {
                return this.SO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SO2Field, value) != true)) {
                    this.SO2Field = value;
                    this.RaisePropertyChanged("SO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimePoint {
            get {
                return this.TimePointField;
            }
            set {
                if ((this.TimePointField.Equals(value) != true)) {
                    this.TimePointField = value;
                    this.RaisePropertyChanged("TimePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unheathful {
            get {
                return this.UnheathfulField;
            }
            set {
                if ((object.ReferenceEquals(this.UnheathfulField, value) != true)) {
                    this.UnheathfulField = value;
                    this.RaisePropertyChanged("Unheathful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityDayAQIPublishLive", Namespace="http://schemas.datacontract.org/2004/07/Xin.AQS.ClassLibrary")]
    [System.SerializableAttribute()]
    public partial class CityDayAQIPublishLive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_8h_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnheathfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((object.ReferenceEquals(this.AQIField, value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_24h {
            get {
                return this.CO_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_24hField, value) != true)) {
                    this.CO_24hField = value;
                    this.RaisePropertyChanged("CO_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityCode {
            get {
                return this.CityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CityCodeField, value) != true)) {
                    this.CityCodeField = value;
                    this.RaisePropertyChanged("CityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Measure {
            get {
                return this.MeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasureField, value) != true)) {
                    this.MeasureField = value;
                    this.RaisePropertyChanged("Measure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2_24h {
            get {
                return this.NO2_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.NO2_24hField, value) != true)) {
                    this.NO2_24hField = value;
                    this.RaisePropertyChanged("NO2_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_8h_24h {
            get {
                return this.O3_8h_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_8h_24hField, value) != true)) {
                    this.O3_8h_24hField = value;
                    this.RaisePropertyChanged("O3_8h_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10_24h {
            get {
                return this.PM10_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.PM10_24hField, value) != true)) {
                    this.PM10_24hField = value;
                    this.RaisePropertyChanged("PM10_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5_24h {
            get {
                return this.PM2_5_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5_24hField, value) != true)) {
                    this.PM2_5_24hField = value;
                    this.RaisePropertyChanged("PM2_5_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryPollutant {
            get {
                return this.PrimaryPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPollutantField, value) != true)) {
                    this.PrimaryPollutantField = value;
                    this.RaisePropertyChanged("PrimaryPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityField, value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2_24h {
            get {
                return this.SO2_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.SO2_24hField, value) != true)) {
                    this.SO2_24hField = value;
                    this.RaisePropertyChanged("SO2_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimePoint {
            get {
                return this.TimePointField;
            }
            set {
                if ((this.TimePointField.Equals(value) != true)) {
                    this.TimePointField = value;
                    this.RaisePropertyChanged("TimePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unheathful {
            get {
                return this.UnheathfulField;
            }
            set {
                if ((object.ReferenceEquals(this.UnheathfulField, value) != true)) {
                    this.UnheathfulField = value;
                    this.RaisePropertyChanged("Unheathful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NationalAQIPublishDataService.ISyncService")]
    public interface ISyncService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/SyncCityAQIPublishLive", ReplyAction="http://tempuri.org/ISyncService/SyncCityAQIPublishLiveResponse")]
        Xin.Basic.NationalAQIPublishDataService.CityAQIPublishLive[] SyncCityAQIPublishLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/SyncCityAQIPublishHistory", ReplyAction="http://tempuri.org/ISyncService/SyncCityAQIPublishHistoryResponse")]
        Xin.Basic.NationalAQIPublishDataService.CityAQIPublishLive[] SyncCityAQIPublishHistory(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/SyncCityDayAQIPublishLive", ReplyAction="http://tempuri.org/ISyncService/SyncCityDayAQIPublishLiveResponse")]
        Xin.Basic.NationalAQIPublishDataService.CityDayAQIPublishLive[] SyncCityDayAQIPublishLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/SyncCityDayAQIPublishHistory", ReplyAction="http://tempuri.org/ISyncService/SyncCityDayAQIPublishHistoryResponse")]
        Xin.Basic.NationalAQIPublishDataService.CityDayAQIPublishLive[] SyncCityDayAQIPublishHistory(System.DateTime beginTime, System.DateTime endTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISyncServiceChannel : Xin.Basic.NationalAQIPublishDataService.ISyncService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncServiceClient : System.ServiceModel.ClientBase<Xin.Basic.NationalAQIPublishDataService.ISyncService>, Xin.Basic.NationalAQIPublishDataService.ISyncService {
        
        public SyncServiceClient() {
        }
        
        public SyncServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Xin.Basic.NationalAQIPublishDataService.CityAQIPublishLive[] SyncCityAQIPublishLive() {
            return base.Channel.SyncCityAQIPublishLive();
        }
        
        public Xin.Basic.NationalAQIPublishDataService.CityAQIPublishLive[] SyncCityAQIPublishHistory(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.SyncCityAQIPublishHistory(beginTime, endTime);
        }
        
        public Xin.Basic.NationalAQIPublishDataService.CityDayAQIPublishLive[] SyncCityDayAQIPublishLive() {
            return base.Channel.SyncCityDayAQIPublishLive();
        }
        
        public Xin.Basic.NationalAQIPublishDataService.CityDayAQIPublishLive[] SyncCityDayAQIPublishHistory(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.SyncCityDayAQIPublishHistory(beginTime, endTime);
        }
    }
}
